TASK_NAME=$1
METHOD="ACT_BC_LANG"
NUM_DEMOS=$2
IMAGE_SIZE=128
BATCH_SIZE=16
DEMO_PATH="$PERACT_BIMANUAL_ROOT/$3"
MASTER_PORT=$4
SEED=$5
RUN_NAME="$6${SEED}"
CHUNK_SIZE=$7
TEMPORAL_AGG=$8
CUDA_DEVICE=$9

CUDA_VISIBLE_DEVICES=${CUDA_DEVICE} python train.py \
method=${METHOD} \
method.train_demo_path=${DEMO_PATH} \
method.lr=0.00001 \
method.num_queries=${CHUNK_SIZE} \
method.chunk_size=${CHUNK_SIZE} \
method.next_action_horizon=${CHUNK_SIZE} \
rlbench.tasks=[${TASK_NAME}] \
rlbench.task_name=$(date +"%Y")_$(date +"%m")_$(date +"%d")_$(date +"%H")_$(date +"%M")_${TASK_NAME}_${RUN_NAME} \
rlbench.demos=${NUM_DEMOS} \
rlbench.demo_path=${DEMO_PATH} \
rlbench.episode_length=400 \
rlbench.camera_resolution=[${IMAGE_SIZE},${IMAGE_SIZE}] \
rlbench.cameras=[wrist_right,wrist_left,front] \
framework.logdir=/project2/seita_1561/temp \
framework.training_iterations=100 \
framework.save_freq=10 \
framework.log_freq=50 \
framework.num_weights_to_keep=100 \
replay.path=/tmp/replay_${MASTER_PORT} \
replay.batch_size=${BATCH_SIZE} \
framework.wandb_logging=False
 \
ddp.master_port=${MASTER_PORT} \
framework.start_seed=${SEED}