seed=11
master_port=23006

python ../train.py \
    method=VOXACTB \
    rlbench.tasks=[bimanual_transfer_item] \
    rlbench.task_name=testing_10_${seed}_stabilizing \
    rlbench.cameras=[overhead,wrist_left,wrist_right]\
    rlbench.demos=1 \
    rlbench.demo_path=$STORE_ROOT/peractvox_data/train \
    rlbench.scene_bounds=[-0.8,-1.0,0.8,1.2,1.0,2.8] \
    replay.batch_size=1 \
    replay.path=/tmp/replay_${master_port} \
    replay.max_parallel_processes=16 \
    method.voxel_sizes=[50] \
    method.voxel_patch_size=5 \
    method.voxel_patch_stride=5 \
    method.num_latents=2048 \
    method.transform_augmentation.apply_se3=True \
    method.transform_augmentation.aug_rpy=[0.0,0.0,45.0] \
    method.pos_encoding_with_lang=True \
    method.which_arm=assistive \
    method.crop_target_obj_voxel=True \
    method.crop_radius=0.4 \
    method.arm_pred_loss=True \
    method.stopped_buffer_timesteps_overwrite=15 \
    method.low_dim_size=4 \
    framework.training_iterations=100 \
    framework.num_weights_to_keep=100 \
    framework.start_seed=${seed} \
    framework.log_freq=10 \
    framework.save_freq=50 \
    framework.logdir=$STORE_ROOT/templogs/ \
    framework.csv_logging=True \
    framework.tensorboard_logging=False \
    framework.wandb_logging=False \
    framework.load_existing_weights=True \
    ddp.num_devices=1 \
    ddp.master_port=${master_port} \
    ddp.master_addr=localhost 